### ISSUE TITLE
Update Clair logo to official version

### ISSUE THREAD

**Issue by jakedt** [wemanity-belgium/hyperclair#30]
Hi,

We've recently unveiled an official Clair logo as part of the Clair 1.0 release. Would you mind updating the logo in your diagram with the released version?

Here is a link to a rasterization of the horizontal logo intended for use on a white background:
https://github.com/coreos/clair/blob/master/img/Clair_horizontal_color.png

Please let me know if you would prefer a stacked or vector version instead.

Thanks!

**Comment by jgsqware** [comment]
I will integrate the png soon! Thanks for the link
