### ISSUE TITLE
Some image name is not working 

### ISSUE THREAD

**Issue by jgsqware** [wemanity-belgium/hyperclair#48]
docker.io/golang
registry:5000/google/cadvisor

**Comment by jgsqware** [comment]
@mv012004 docker.io is your local registry or the image name?

**Comment by jgsqware** [comment]
For official images, I think we can't pull layer.  Need to double check. However, I will put better log/error for that. 
Moreover,  official images are already tested by docker itself. 

Finally, docker.io in the name is handle as official image (docker.io is removed from the name when it's tagged) 

registry:5000/google/cadvisor name is handle correctly

**Comment by mv012004** [comment]
nope.. i have my registry running on a different server, like abc.com/google/cadvisor

**Comment by jgsqware** [comment]
Yes for google/cadvisor it's another problem then the image naming.

Is it the official one that you pushed on your own registry?
