### ISSUE TITLE
Refactor the Json Report

### ISSUE THREAD

**Issue by jgsqware** [wemanity-belgium/hyperclair#6]
@npirotte: Voici le JSON https://gist.github.com/jgsqware/694e9b92dcdaddb88adf

L'idée est de créer un rapport un peu joli.

Pour le moment j'ai çà: 
![hyperclair report](https://cloud.githubusercontent.com/assets/3304363/12650207/36f94532-c5e2-11e5-8e77-189a2774f62b.png)

J'aimerai avoir quelque chose de plus sympa. J'aime beaucoup l'interface de Nautilus de Docker
![Nautilus](http://image.slidesharecdn.com/vqgukv6erdcyzfqed1yc-signature-0edb414cce8bc2684c4cd6c874d3252e884a6cab9109bf9c0d2732f819a5f48e-poli-151123211259-lva1-app6892/95/dockercon-eu-2015-official-repos-and-project-nautilus-38-638.jpg?cb=1449082523)

Un truc dans le genre avec des couleurs pour les vulnérabilités c'est assez cool!

On peut en discuter ici

**Comment by Quentin-M** [comment]
Bonjour,

Je suis tres enthousiaste vis-a-vis de votre travail !

Je me permet de répondre à ce sujet pour vous avertir que nous sommes en train de travailler sur la version 1.0 de Clair qui devrait sortir en version stable d'ici quelques semaines (travail en cours pour l'instant visible à https://github.com/Quentin-M/clair/tree/sql). Celle-ci améliore grandement les performances et offre de nouvelles informations. Elle modifie aussi profondément son API (https://gist.github.com/jzelinskie/71e51f0429b6b4318d66) et devrait vous permettre de générer une interface beaucoup plus ergonomique!

Notez que les vulnérabilités apparaissent maintenant directement sous les paquets affectés par celles-ci et que les versions des paquets corrigeant les vulnerabilités (si disponible) sont également specifiées (`FixedBy`).

Je reste à votre disposition pour toute information complémentaire.

**Comment by jgsqware** [comment]
Awesome @Quentin-M! Je vais suivre de près ces évolutions pour les intégrer ;) !

**Comment by npirotte** [comment]
@jgsqware vu que la date du fest approche tout doucement j'aimerai arriver à une 1er release pour le template, même si ça sera à faire évoluer par la suite :)

Tu sais faire un checkout de la branche et me dire ce que tu en penses, ce qu'il faudrait changer et tout et tout ?

**Comment by jgsqware** [comment]
Je vais tenter de faire un check cette aprem ! Merci!

**Comment by jgsqware** [comment]
je te propose de faire un pull request d'ailleurs @npirotte :)

**Comment by npirotte** [comment]
Ok c'est partit !
