### ISSUE TITLE
Https for registry

### ISSUE THREAD

**Issue by sbehrens** [wemanity-belgium/hyperclair#75]
```
sbehrens@lgml-sbehrens3 ~/work/bin$ ./hyperclair pull myspecial.registry.net:7002/skynet_test:latest                                                                                                             1 ↵
service is unavailable
FATA[0000] pulling image myspecial.registry:7002/skynet_test:latest: 400 - <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

Seems to not be using TLS by default.  do not see a configuration example or config setting for this.

**Comment by jgsqware** [comment]
You're right the TLS is not activated by default. 
Need to investigate how to activate it. 

you could try to add `auth.insecureSkipVerify: false` in your hyperclair.yml config file

**Comment by sbehrens** [comment]
sounds good, thanks.

**Comment by peceka** [comment]
Hi,

can you explain how to achive it? Right now I've got such configuration:

[root@git2-prod ~]# cat hyperclair.yml
clair:
  port: 6060
  healthPort: 6061
  uri: http://docker2.host
  priority: Low
  report:
    path: ./reports
    format: html
  auth.insecureSkipVerify: false

I've logged to register:
[root@git2-prod ~]# hyperclair login git:5005
Username: docker2
Password:
Login Successful

But can't download image:
[root@git2-prod ~]#hyperclair --config hyperclair.yml pull git:5005/project/phpapp:tag

service is unavailable
FATA[0000] pulling image git:5005/project/phpapp:tag: 400 - <html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>

**Comment by chrisfelix82** [comment]
if strings.Contains(registry, "docker") {
		registry = "https://" + registry + "/v2"

	} else {
		registry = "http://" + registry + "/v2"
	}
This logic seems to prevent HTTPS:// login to a private registry. How can I achieve this?
