### ISSUE TITLE
Add Severity bar in html report

### ISSUE THREAD

**Issue by jgsqware** [wemanity-belgium/hyperclair#77]
As proposed by @Quentin-M, it could be nice to have a severity bar in place of

![screen shot 2016-04-29 at 18 30 11](https://cloud.githubusercontent.com/assets/3304363/14922544/73bdf2f8-0e38-11e6-85bd-32f8b5a6ab94.png)

More or less, 
![](http://x.quentin-machu.fr/2016-04-29_12-07-31.png)

**Comment by npirotte** [comment]
Ok, I think the code is done, but I removed it, I don't know why, it will be quick !

Little precision : Should I include safe features in the total or not ?

## Example
__data:__ 8 features, 4 safe, 2 low, 1 medium 1 high

__result:__ 50% low - 25% Medium - 25% medium (without) vs 50% save - 25% low - 12.5% medium - 12,.5 % High (with)

**Comment by jgsqware** [comment]
You can included for now

**Comment by npirotte** [comment]
@jgsqware pull request created :)
