### ISSUE TITLE
Having problem on pulling image for jgsqware images

### ISSUE THREAD

**Issue by cuteydarling** [wemanity-belgium/hyperclair#88]
Hello,

I'm trying to perform a analyse of an jgsqware image via Hyperclair but it seems that it is not working for me. 

I'm new to Docker as well as CoreOS. Can anyone guide me on this?

Below are the error i got:
![image](https://cloud.githubusercontent.com/assets/17915580/17577077/a63e3ba4-5f71-11e6-8ee6-3e38503daad2.png)

Thank You!!

**Comment by jgsqware** [comment]
👋

apparently you try to pull the jgsqware image from your own registry that
should run
1. in a separate container
2. resolvable as registry on port 5000
3. having push on it the jgsqware image

If it's not the case, it will be easier to get images from docker hub,
there you can use obviously one of the jgsqware image

**Comment by cuteydarling** [comment]
Hi Jgsqware,

Thank you for your reply.

It's working now! The mistake i did was instead of typing in registry:5000, i should put in as localhost:5000 as i created the tag as localhost.

But it seems that there is another problem. When i try to analyse the image, it shows 0 vulnerabilities. Is it possible?
![image](https://cloud.githubusercontent.com/assets/17915580/17603711/644bdfbe-600a-11e6-87b5-50c1e33ad859.png)

Thank You.
