### ISSUE TITLE
hyperclair login not working with amazon ecr service

### ISSUE THREAD

**Issue by pandeybk** [wemanity-belgium/hyperclair#95]
I am trying to login to hyperclair as follows:

With https I am seeing following output
`
hyperclair login https://<account>.dkr.ecr.us-west-2.amazonaws.com
`
`
Username: AWS
Password:  
client quit unexpectedly
FATA[0016] log in: log in http://https://<account>.dkr.ecr.us-west-2.amazonaws.com/v2: Get http://https://<account>.dkr.ecr.us-west-2.amazonaws.com/v2: dial tcp: unknown port tcp/ 
`

Without https it wait for longer period, looks like it is trying to communicate at port 80 which is not allowed in case of ecr. 
`
hyperclair login <account>.dkr.ecr.us-west-2.amazonaws.com
`

**Comment by jgsqware** [comment]
Hello,

currently Hyperclair is deprecated. Could you check it with github.com/jgsqware/clairctl.

Thanks

**Comment by jgsqware** [comment]
However, with clairctl, you will logged first with docker, than it will work automatically
