### ISSUE TITLE
malformed HTTP response

### ISSUE THREAD

**Issue by celevra** [wemanity-belgium/hyperclair#96]
Hi,

normal work is possible with the registry but i can't pull with hyperclair, i get:
FATA[0000] pulling image xxx:5000/keen-fs: retrieving manifest: Get http://xxx:5000/v2/keen-fs/manifests/latest: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

is there something else i can provide to dig deeper into the problem?

regards

celevra

**Comment by jgsqware** [comment]
Hello this project has move to GitHub.com/jgsqware/clairctl

Could you check with this version?

Thanks

**Comment by celevra** [comment]
thanks for the fast answer, i will try it asap, but first i have to build it ;-)
